import Head from "next/head";
import styles from "../../styles/about.module.css";
import Nav from "../../Components/nav";
import { Card, Icon, Image, Grid } from "semantic-ui-react";

export default function Other() {
  const cards = [
    {
      img: "/IMG_0005.jpeg",
      date: "December 2019",
      description: "first day at home",
    },
    {
      img: "/f0747372-3159-487f-87d3-d18fa2796cd5.jpeg",
      date: "December 2019",
      description: "first day at home",
    },
    {
      img: "/IMG_6022.jpeg",
      date: "January 2020",
      description: "first time at the vet",
    },
    {
      img: "/IMG_5559.jpeg",
      date: "January 2020",
      description: "learning to sit",
    },
    {
      img: "/IMG_4868.jpeg",
      date: "December 2019",
      description: "journey home",
    },

    {
      img: "/IMG_5055.jpeg",
      date: "December 2019",
      description: "potty training",
    },
    {
      img: "/IMG_5226.jpeg",
      date: "December 2019",
      description: "baby teeth",
    },
    {
      img: "/IMG_9320.jpeg",
      date: "June 2020",
      description: "faded",
    },
  ];
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link
          rel="stylesheet"
          href="https://cdn.jsdelivr.net/npm/semantic-ui@2.4.2/dist/semantic.min.css"
        />
      </Head>
      <Nav />
      <main className={styles.main}>
        <Grid>
          <Grid.Row columns={4}>
            {cards.map((robbiecard) => {
              return (
                <Grid.Column>
                  <Card>
                    <Image src={robbiecard.img} wrapped ui={false} />
                    <Card.Content>
                      <Card.Meta>{robbiecard.date}</Card.Meta>
                      <Card.Description>
                        {robbiecard.description}
                      </Card.Description>
                    </Card.Content>
                  </Card>
                </Grid.Column>
              );
            })}
          </Grid.Row>
        </Grid>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}
