import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link
          rel="stylesheet"
          href="https://cdn.jsdelivr.net/npm/semantic-ui@2.4.2/dist/semantic.min.css"
        />
      </Head>
      <div className={"ui pointing menu " + styles.nav} >
        <a className="active item">Home</a>
        <a className="item" href="/about"> About</a>
        <a className="item">Gallery</a>
        <a className="item">Puppy Essentials</a>
      </div>

      <main className={styles.main}>
        {/* <h1 className={styles.title}>Welcome to Robbie's World</h1> */}
        <div className={styles.banner}>
          <h1 className={styles.title}>Welcome to Robbie's World</h1>
          <div className={styles.bgimage}></div>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}
