import React from "react";
import Nav from "../Components/nav";
import Head from "next/head";
import { Button, Card, Image, Icon } from "semantic-ui-react";

const shoppingItems = [
  {
    image: "https://m.media-amazon.com/images/I/717RcBICv4L._AC_SL1500_.jpg",
    name: "Mad Scientist Toy for Dogs",
    link: "https://www.amazon.ca/Trixie-32019-Scientist-Level-White/dp/B003TOKTEG/ref=sr_1_3?keywords=mad+scientist+dog+toy&qid=1642354915&sprefix=mad+scientist+%2Caps%2C85&sr=8-3",
  },
];

export default function Favourites() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link
          rel="stylesheet"
          href="https://cdn.jsdelivr.net/npm/semantic-ui@2.4.2/dist/semantic.min.css"
        />
      </Head>
      <Nav />
      <main>
        <Card.Group>
          {shoppingItems.map((item) => {
            return (
              <Card>
                <a href={item.link}>
                  <Image src={item.image} wrapped ui={false} />
                </a>

                <Card.Content>
                  <Card.Header>{item.name}</Card.Header>
                  <Card.Meta>Joined in 2016</Card.Meta>
                  <Card.Description>
                    Daniel is a comedian living in Nashville.
                  </Card.Description>
                </Card.Content>
                <Card.Content extra>
                  <a>
                    <Icon name="user" />
                    10 Friends
                  </a>
                </Card.Content>
              </Card>
            );
          })}
        </Card.Group>
      </main>
    </div>
  );
}
